Implement account_size/0
niklaslong/olm-ex pull request #8
Opened 2020-08-13 15:20 UTC by niklaslong

2020-08-13 22:24 UTC, fancycade requested changes
Good start! Had to do some research on the int typing. Looks like ulong will be the most generic so that is fine.

We should probably make version use enif_make_uint instead of enif_make_int now that I think about it. I didn't look far enough in the erlang docs :sweat_smile:

2020-08-13 22:24 UTC, fancycade commented on lib/olm.ex
> +  def utility_size(), do: error("utiliy_size/0")
Misspelled utility in the error message

2020-08-13 22:24 UTC, fancycade commented on native/src/olm_nifs.c
> +	return enif_make_ulong(env, size);
Spacing isn't aligned.

2020-08-13 22:24 UTC, fancycade commented on lib/olm.ex
> +  The size of an utiliy object in bytes.
Misspelled utility in doc

2020-08-14 08:16 UTC, niklaslong commented on lib/olm.ex
> +  def utility_size(), do: error("utiliy_size/0")
Good eye! 👀

2020-08-14 09:03 UTC, niklaslong commented
@fancycade I've added a simple clang-format, let me know if you have particular preferences you think should be included. I've mostly based it on Webkit and Mozilla styles with 4 char indent à la Rust. Here's a good tool to play around with configuration: https://zed0.co.uk/clang-format-configurator/

Formatting Elixir + C files can be done with `mix fmt`.

2020-08-14 18:54 UTC, fancycade approved these changes

2020-08-14 20:12 UTC, merged